apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git-codecommit.il-central-1.amazonaws.com/v1/repos/lab-commit-repo
    targetRevision: main
    path: helm/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-commit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
